// Generated by cpp11: do not edit by hand
// clang-format off

#include "mdgm_types.hpp"
#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// R_model.cpp
cpp11::external_pointer<mdgm::Model> model_create_standalone_cpp(cpp11::external_pointer<mdgm::NaturalUndirectedGraph> nug, cpp11::strings dag_type, int n_colors);
extern "C" SEXP _mdgm_model_create_standalone_cpp(SEXP nug, SEXP dag_type, SEXP n_colors) {
  BEGIN_CPP11
    return cpp11::as_sexp(model_create_standalone_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::NaturalUndirectedGraph>>>(nug), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(dag_type), cpp11::as_cpp<cpp11::decay_t<int>>(n_colors)));
  END_CPP11
}
// R_model.cpp
cpp11::external_pointer<mdgm::Model> model_create_hierarchical_cpp(cpp11::external_pointer<mdgm::NaturalUndirectedGraph> nug, cpp11::strings dag_type, int n_colors, cpp11::strings emission);
extern "C" SEXP _mdgm_model_create_hierarchical_cpp(SEXP nug, SEXP dag_type, SEXP n_colors, SEXP emission) {
  BEGIN_CPP11
    return cpp11::as_sexp(model_create_hierarchical_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::NaturalUndirectedGraph>>>(nug), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(dag_type), cpp11::as_cpp<cpp11::decay_t<int>>(n_colors), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(emission)));
  END_CPP11
}
// R_model.cpp
cpp11::external_pointer<mdgm::Model> model_create_mrf_standalone_cpp(cpp11::external_pointer<mdgm::NaturalUndirectedGraph> nug, cpp11::strings method, int n_colors, int n_aux_sweeps);
extern "C" SEXP _mdgm_model_create_mrf_standalone_cpp(SEXP nug, SEXP method, SEXP n_colors, SEXP n_aux_sweeps) {
  BEGIN_CPP11
    return cpp11::as_sexp(model_create_mrf_standalone_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::NaturalUndirectedGraph>>>(nug), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(method), cpp11::as_cpp<cpp11::decay_t<int>>(n_colors), cpp11::as_cpp<cpp11::decay_t<int>>(n_aux_sweeps)));
  END_CPP11
}
// R_model.cpp
cpp11::external_pointer<mdgm::Model> model_create_mrf_hierarchical_cpp(cpp11::external_pointer<mdgm::NaturalUndirectedGraph> nug, cpp11::strings method, int n_colors, cpp11::strings emission, int n_aux_sweeps);
extern "C" SEXP _mdgm_model_create_mrf_hierarchical_cpp(SEXP nug, SEXP method, SEXP n_colors, SEXP emission, SEXP n_aux_sweeps) {
  BEGIN_CPP11
    return cpp11::as_sexp(model_create_mrf_hierarchical_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::NaturalUndirectedGraph>>>(nug), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(method), cpp11::as_cpp<cpp11::decay_t<int>>(n_colors), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(emission), cpp11::as_cpp<cpp11::decay_t<int>>(n_aux_sweeps)));
  END_CPP11
}
// R_model.cpp
bool model_has_emission_cpp(cpp11::external_pointer<mdgm::Model> model);
extern "C" SEXP _mdgm_model_has_emission_cpp(SEXP model) {
  BEGIN_CPP11
    return cpp11::as_sexp(model_has_emission_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::Model>>>(model)));
  END_CPP11
}
// R_model.cpp
int model_nvertices_cpp(cpp11::external_pointer<mdgm::Model> model);
extern "C" SEXP _mdgm_model_nvertices_cpp(SEXP model) {
  BEGIN_CPP11
    return cpp11::as_sexp(model_nvertices_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::Model>>>(model)));
  END_CPP11
}
// R_model.cpp
int model_ncolors_cpp(cpp11::external_pointer<mdgm::Model> model);
extern "C" SEXP _mdgm_model_ncolors_cpp(SEXP model) {
  BEGIN_CPP11
    return cpp11::as_sexp(model_ncolors_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::Model>>>(model)));
  END_CPP11
}
// R_model.cpp
cpp11::sexp model_emission_type_cpp(cpp11::external_pointer<mdgm::Model> model);
extern "C" SEXP _mdgm_model_emission_type_cpp(SEXP model) {
  BEGIN_CPP11
    return cpp11::as_sexp(model_emission_type_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::Model>>>(model)));
  END_CPP11
}
// R_model.cpp
cpp11::writable::list run_mcmc_cpp(cpp11::external_pointer<mdgm::Model> model, const cpp11::doubles& obs_data, const cpp11::integers& obs_ptr, const cpp11::integers& z_init, double psi_init, const cpp11::doubles& theta_init, int n_iterations, double psi_tune, const cpp11::doubles& emission_prior_params, cpp11::external_pointer<mdgm::RNG> rng);
extern "C" SEXP _mdgm_run_mcmc_cpp(SEXP model, SEXP obs_data, SEXP obs_ptr, SEXP z_init, SEXP psi_init, SEXP theta_init, SEXP n_iterations, SEXP psi_tune, SEXP emission_prior_params, SEXP rng) {
  BEGIN_CPP11
    return cpp11::as_sexp(run_mcmc_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::Model>>>(model), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(obs_data), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(obs_ptr), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(z_init), cpp11::as_cpp<cpp11::decay_t<double>>(psi_init), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(theta_init), cpp11::as_cpp<cpp11::decay_t<int>>(n_iterations), cpp11::as_cpp<cpp11::decay_t<double>>(psi_tune), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(emission_prior_params), cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::RNG>>>(rng)));
  END_CPP11
}
// R_natural_undirected_graph.cpp
cpp11::external_pointer<mdgm::NaturalUndirectedGraph> nug_create_cpp(int nvertices, const cpp11::integers& row, const cpp11::integers& col, const cpp11::doubles& weights);
extern "C" SEXP _mdgm_nug_create_cpp(SEXP nvertices, SEXP row, SEXP col, SEXP weights) {
  BEGIN_CPP11
    return cpp11::as_sexp(nug_create_cpp(cpp11::as_cpp<cpp11::decay_t<int>>(nvertices), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(row), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(col), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights)));
  END_CPP11
}
// R_natural_undirected_graph.cpp
cpp11::writable::list nug_sample_spanning_tree_cpp(cpp11::external_pointer<mdgm::NaturalUndirectedGraph> g, cpp11::strings method, int k, cpp11::external_pointer<mdgm::RNG> rng);
extern "C" SEXP _mdgm_nug_sample_spanning_tree_cpp(SEXP g, SEXP method, SEXP k, SEXP rng) {
  BEGIN_CPP11
    return cpp11::as_sexp(nug_sample_spanning_tree_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::NaturalUndirectedGraph>>>(g), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(method), cpp11::as_cpp<cpp11::decay_t<int>>(k), cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::RNG>>>(rng)));
  END_CPP11
}
// R_natural_undirected_graph.cpp
cpp11::writable::integers nug_neighbors_cpp(cpp11::external_pointer<mdgm::NaturalUndirectedGraph> g, int vertex);
extern "C" SEXP _mdgm_nug_neighbors_cpp(SEXP g, SEXP vertex) {
  BEGIN_CPP11
    return cpp11::as_sexp(nug_neighbors_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::NaturalUndirectedGraph>>>(g), cpp11::as_cpp<cpp11::decay_t<int>>(vertex)));
  END_CPP11
}
// R_natural_undirected_graph.cpp
cpp11::writable::doubles nug_neighbor_weights_cpp(cpp11::external_pointer<mdgm::NaturalUndirectedGraph> g, int vertex);
extern "C" SEXP _mdgm_nug_neighbor_weights_cpp(SEXP g, SEXP vertex) {
  BEGIN_CPP11
    return cpp11::as_sexp(nug_neighbor_weights_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::NaturalUndirectedGraph>>>(g), cpp11::as_cpp<cpp11::decay_t<int>>(vertex)));
  END_CPP11
}
// R_natural_undirected_graph.cpp
cpp11::external_pointer<mdgm::NaturalUndirectedGraph> nug_generate_regular_cpp(int nrows, int ncols, int order);
extern "C" SEXP _mdgm_nug_generate_regular_cpp(SEXP nrows, SEXP ncols, SEXP order) {
  BEGIN_CPP11
    return cpp11::as_sexp(nug_generate_regular_cpp(cpp11::as_cpp<cpp11::decay_t<int>>(nrows), cpp11::as_cpp<cpp11::decay_t<int>>(ncols), cpp11::as_cpp<cpp11::decay_t<int>>(order)));
  END_CPP11
}
// R_natural_undirected_graph.cpp
int nug_nvertices_cpp(cpp11::external_pointer<mdgm::NaturalUndirectedGraph> g);
extern "C" SEXP _mdgm_nug_nvertices_cpp(SEXP g) {
  BEGIN_CPP11
    return cpp11::as_sexp(nug_nvertices_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::NaturalUndirectedGraph>>>(g)));
  END_CPP11
}
// R_natural_undirected_graph.cpp
int nug_nedges_cpp(cpp11::external_pointer<mdgm::NaturalUndirectedGraph> g);
extern "C" SEXP _mdgm_nug_nedges_cpp(SEXP g) {
  BEGIN_CPP11
    return cpp11::as_sexp(nug_nedges_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::NaturalUndirectedGraph>>>(g)));
  END_CPP11
}
// R_utils.cpp
cpp11::external_pointer<mdgm::RNG> rng_create_cpp();
extern "C" SEXP _mdgm_rng_create_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(rng_create_cpp());
  END_CPP11
}
// R_utils.cpp
cpp11::external_pointer<mdgm::RNG> rng_create_seed_cpp(int seed);
extern "C" SEXP _mdgm_rng_create_seed_cpp(SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(rng_create_seed_cpp(cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// R_utils.cpp
void rng_set_seed_cpp(cpp11::external_pointer<mdgm::RNG> rng, int seed);
extern "C" SEXP _mdgm_rng_set_seed_cpp(SEXP rng, SEXP seed) {
  BEGIN_CPP11
    rng_set_seed_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::RNG>>>(rng), cpp11::as_cpp<cpp11::decay_t<int>>(seed));
    return R_NilValue;
  END_CPP11
}
// R_utils.cpp
void rng_reseed_random_cpp(cpp11::external_pointer<mdgm::RNG> rng);
extern "C" SEXP _mdgm_rng_reseed_random_cpp(SEXP rng) {
  BEGIN_CPP11
    rng_reseed_random_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::RNG>>>(rng));
    return R_NilValue;
  END_CPP11
}
// R_utils.cpp
double rng_uniform_cpp(cpp11::external_pointer<mdgm::RNG> rng, double a, double b);
extern "C" SEXP _mdgm_rng_uniform_cpp(SEXP rng, SEXP a, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(rng_uniform_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::RNG>>>(rng), cpp11::as_cpp<cpp11::decay_t<double>>(a), cpp11::as_cpp<cpp11::decay_t<double>>(b)));
  END_CPP11
}
// R_utils.cpp
int rng_uniform_int_cpp(cpp11::external_pointer<mdgm::RNG> rng, int a, int b);
extern "C" SEXP _mdgm_rng_uniform_int_cpp(SEXP rng, SEXP a, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(rng_uniform_int_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::RNG>>>(rng), cpp11::as_cpp<cpp11::decay_t<int>>(a), cpp11::as_cpp<cpp11::decay_t<int>>(b)));
  END_CPP11
}
// R_utils.cpp
double rng_normal_cpp(cpp11::external_pointer<mdgm::RNG> rng, double mean, double stddev);
extern "C" SEXP _mdgm_rng_normal_cpp(SEXP rng, SEXP mean, SEXP stddev) {
  BEGIN_CPP11
    return cpp11::as_sexp(rng_normal_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::RNG>>>(rng), cpp11::as_cpp<cpp11::decay_t<double>>(mean), cpp11::as_cpp<cpp11::decay_t<double>>(stddev)));
  END_CPP11
}
// R_utils.cpp
int rng_discrete_cpp(cpp11::external_pointer<mdgm::RNG> rng, const cpp11::doubles& weights);
extern "C" SEXP _mdgm_rng_discrete_cpp(SEXP rng, SEXP weights) {
  BEGIN_CPP11
    return cpp11::as_sexp(rng_discrete_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::RNG>>>(rng), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_mdgm_model_create_hierarchical_cpp",     (DL_FUNC) &_mdgm_model_create_hierarchical_cpp,      4},
    {"_mdgm_model_create_mrf_hierarchical_cpp", (DL_FUNC) &_mdgm_model_create_mrf_hierarchical_cpp,  5},
    {"_mdgm_model_create_mrf_standalone_cpp",   (DL_FUNC) &_mdgm_model_create_mrf_standalone_cpp,    4},
    {"_mdgm_model_create_standalone_cpp",       (DL_FUNC) &_mdgm_model_create_standalone_cpp,        3},
    {"_mdgm_model_emission_type_cpp",           (DL_FUNC) &_mdgm_model_emission_type_cpp,            1},
    {"_mdgm_model_has_emission_cpp",            (DL_FUNC) &_mdgm_model_has_emission_cpp,             1},
    {"_mdgm_model_ncolors_cpp",                 (DL_FUNC) &_mdgm_model_ncolors_cpp,                  1},
    {"_mdgm_model_nvertices_cpp",               (DL_FUNC) &_mdgm_model_nvertices_cpp,                1},
    {"_mdgm_nug_create_cpp",                    (DL_FUNC) &_mdgm_nug_create_cpp,                     4},
    {"_mdgm_nug_generate_regular_cpp",          (DL_FUNC) &_mdgm_nug_generate_regular_cpp,           3},
    {"_mdgm_nug_nedges_cpp",                    (DL_FUNC) &_mdgm_nug_nedges_cpp,                     1},
    {"_mdgm_nug_neighbor_weights_cpp",          (DL_FUNC) &_mdgm_nug_neighbor_weights_cpp,           2},
    {"_mdgm_nug_neighbors_cpp",                 (DL_FUNC) &_mdgm_nug_neighbors_cpp,                  2},
    {"_mdgm_nug_nvertices_cpp",                 (DL_FUNC) &_mdgm_nug_nvertices_cpp,                  1},
    {"_mdgm_nug_sample_spanning_tree_cpp",      (DL_FUNC) &_mdgm_nug_sample_spanning_tree_cpp,       4},
    {"_mdgm_rng_create_cpp",                    (DL_FUNC) &_mdgm_rng_create_cpp,                     0},
    {"_mdgm_rng_create_seed_cpp",               (DL_FUNC) &_mdgm_rng_create_seed_cpp,                1},
    {"_mdgm_rng_discrete_cpp",                  (DL_FUNC) &_mdgm_rng_discrete_cpp,                   2},
    {"_mdgm_rng_normal_cpp",                    (DL_FUNC) &_mdgm_rng_normal_cpp,                     3},
    {"_mdgm_rng_reseed_random_cpp",             (DL_FUNC) &_mdgm_rng_reseed_random_cpp,              1},
    {"_mdgm_rng_set_seed_cpp",                  (DL_FUNC) &_mdgm_rng_set_seed_cpp,                   2},
    {"_mdgm_rng_uniform_cpp",                   (DL_FUNC) &_mdgm_rng_uniform_cpp,                    3},
    {"_mdgm_rng_uniform_int_cpp",               (DL_FUNC) &_mdgm_rng_uniform_int_cpp,                3},
    {"_mdgm_run_mcmc_cpp",                      (DL_FUNC) &_mdgm_run_mcmc_cpp,                      10},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_mdgm(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
