// Generated by cpp11: do not edit by hand
// clang-format off

#include "mdgm_types.hpp"
#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// R_undirected_graph.cpp
cpp11::external_pointer<mdgm::UndirectedGraph> undirected_graph_create_cpp(int nvertices, const cpp11::integers& row, const cpp11::integers& col, const cpp11::doubles& weights);
extern "C" SEXP _mdgm_undirected_graph_create_cpp(SEXP nvertices, SEXP row, SEXP col, SEXP weights) {
  BEGIN_CPP11
    return cpp11::as_sexp(undirected_graph_create_cpp(cpp11::as_cpp<cpp11::decay_t<int>>(nvertices), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(row), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(col), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights)));
  END_CPP11
}
// R_undirected_graph.cpp
cpp11::writable::list undirected_graph_sample_spanning_tree_cpp(cpp11::external_pointer<mdgm::UndirectedGraph> g, cpp11::strings method, int k, cpp11::external_pointer<mdgm::RNG> rng);
extern "C" SEXP _mdgm_undirected_graph_sample_spanning_tree_cpp(SEXP g, SEXP method, SEXP k, SEXP rng) {
  BEGIN_CPP11
    return cpp11::as_sexp(undirected_graph_sample_spanning_tree_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::UndirectedGraph>>>(g), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(method), cpp11::as_cpp<cpp11::decay_t<int>>(k), cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::RNG>>>(rng)));
  END_CPP11
}
// R_undirected_graph.cpp
cpp11::writable::list undirected_graph_neighbors_cpp(cpp11::external_pointer<mdgm::UndirectedGraph> g, int vertex);
extern "C" SEXP _mdgm_undirected_graph_neighbors_cpp(SEXP g, SEXP vertex) {
  BEGIN_CPP11
    return cpp11::as_sexp(undirected_graph_neighbors_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::UndirectedGraph>>>(g), cpp11::as_cpp<cpp11::decay_t<int>>(vertex)));
  END_CPP11
}
// R_undirected_graph.cpp
int undirected_graph_nvertices_cpp(cpp11::external_pointer<mdgm::UndirectedGraph> g);
extern "C" SEXP _mdgm_undirected_graph_nvertices_cpp(SEXP g) {
  BEGIN_CPP11
    return cpp11::as_sexp(undirected_graph_nvertices_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::UndirectedGraph>>>(g)));
  END_CPP11
}
// R_undirected_graph.cpp
int undirected_graph_nedges_cpp(cpp11::external_pointer<mdgm::UndirectedGraph> g);
extern "C" SEXP _mdgm_undirected_graph_nedges_cpp(SEXP g) {
  BEGIN_CPP11
    return cpp11::as_sexp(undirected_graph_nedges_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::UndirectedGraph>>>(g)));
  END_CPP11
}
// R_utils.cpp
cpp11::external_pointer<mdgm::RNG> rng_create_cpp();
extern "C" SEXP _mdgm_rng_create_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(rng_create_cpp());
  END_CPP11
}
// R_utils.cpp
cpp11::external_pointer<mdgm::RNG> rng_create_seed_cpp(int seed);
extern "C" SEXP _mdgm_rng_create_seed_cpp(SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(rng_create_seed_cpp(cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// R_utils.cpp
void rng_set_seed_cpp(cpp11::external_pointer<mdgm::RNG> rng, int seed);
extern "C" SEXP _mdgm_rng_set_seed_cpp(SEXP rng, SEXP seed) {
  BEGIN_CPP11
    rng_set_seed_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::RNG>>>(rng), cpp11::as_cpp<cpp11::decay_t<int>>(seed));
    return R_NilValue;
  END_CPP11
}
// R_utils.cpp
void rng_reseed_random_cpp(cpp11::external_pointer<mdgm::RNG> rng);
extern "C" SEXP _mdgm_rng_reseed_random_cpp(SEXP rng) {
  BEGIN_CPP11
    rng_reseed_random_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::RNG>>>(rng));
    return R_NilValue;
  END_CPP11
}
// R_utils.cpp
double rng_uniform_cpp(cpp11::external_pointer<mdgm::RNG> rng, double a, double b);
extern "C" SEXP _mdgm_rng_uniform_cpp(SEXP rng, SEXP a, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(rng_uniform_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::RNG>>>(rng), cpp11::as_cpp<cpp11::decay_t<double>>(a), cpp11::as_cpp<cpp11::decay_t<double>>(b)));
  END_CPP11
}
// R_utils.cpp
int rng_uniform_int_cpp(cpp11::external_pointer<mdgm::RNG> rng, int a, int b);
extern "C" SEXP _mdgm_rng_uniform_int_cpp(SEXP rng, SEXP a, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(rng_uniform_int_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::RNG>>>(rng), cpp11::as_cpp<cpp11::decay_t<int>>(a), cpp11::as_cpp<cpp11::decay_t<int>>(b)));
  END_CPP11
}
// R_utils.cpp
double rng_normal_cpp(cpp11::external_pointer<mdgm::RNG> rng, double mean, double stddev);
extern "C" SEXP _mdgm_rng_normal_cpp(SEXP rng, SEXP mean, SEXP stddev) {
  BEGIN_CPP11
    return cpp11::as_sexp(rng_normal_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::RNG>>>(rng), cpp11::as_cpp<cpp11::decay_t<double>>(mean), cpp11::as_cpp<cpp11::decay_t<double>>(stddev)));
  END_CPP11
}
// R_utils.cpp
int rng_discrete_cpp(cpp11::external_pointer<mdgm::RNG> rng, const cpp11::doubles& weights);
extern "C" SEXP _mdgm_rng_discrete_cpp(SEXP rng, SEXP weights) {
  BEGIN_CPP11
    return cpp11::as_sexp(rng_discrete_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<mdgm::RNG>>>(rng), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_mdgm_rng_create_cpp",                            (DL_FUNC) &_mdgm_rng_create_cpp,                            0},
    {"_mdgm_rng_create_seed_cpp",                       (DL_FUNC) &_mdgm_rng_create_seed_cpp,                       1},
    {"_mdgm_rng_discrete_cpp",                          (DL_FUNC) &_mdgm_rng_discrete_cpp,                          2},
    {"_mdgm_rng_normal_cpp",                            (DL_FUNC) &_mdgm_rng_normal_cpp,                            3},
    {"_mdgm_rng_reseed_random_cpp",                     (DL_FUNC) &_mdgm_rng_reseed_random_cpp,                     1},
    {"_mdgm_rng_set_seed_cpp",                          (DL_FUNC) &_mdgm_rng_set_seed_cpp,                          2},
    {"_mdgm_rng_uniform_cpp",                           (DL_FUNC) &_mdgm_rng_uniform_cpp,                           3},
    {"_mdgm_rng_uniform_int_cpp",                       (DL_FUNC) &_mdgm_rng_uniform_int_cpp,                       3},
    {"_mdgm_undirected_graph_create_cpp",               (DL_FUNC) &_mdgm_undirected_graph_create_cpp,               4},
    {"_mdgm_undirected_graph_nedges_cpp",               (DL_FUNC) &_mdgm_undirected_graph_nedges_cpp,               1},
    {"_mdgm_undirected_graph_neighbors_cpp",            (DL_FUNC) &_mdgm_undirected_graph_neighbors_cpp,            2},
    {"_mdgm_undirected_graph_nvertices_cpp",            (DL_FUNC) &_mdgm_undirected_graph_nvertices_cpp,            1},
    {"_mdgm_undirected_graph_sample_spanning_tree_cpp", (DL_FUNC) &_mdgm_undirected_graph_sample_spanning_tree_cpp, 4},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_mdgm(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
