# Generated by cpp11: do not edit by hand

model_create_standalone_cpp <- function(nug, dag_type, n_colors) {
  .Call(`_mdgm_model_create_standalone_cpp`, nug, dag_type, n_colors)
}

model_create_hierarchical_cpp <- function(nug, dag_type, n_colors, emission) {
  .Call(`_mdgm_model_create_hierarchical_cpp`, nug, dag_type, n_colors, emission)
}

model_create_mrf_standalone_cpp <- function(nug, method, n_colors, n_aux_sweeps) {
  .Call(`_mdgm_model_create_mrf_standalone_cpp`, nug, method, n_colors, n_aux_sweeps)
}

model_create_mrf_hierarchical_cpp <- function(nug, method, n_colors, emission, n_aux_sweeps) {
  .Call(`_mdgm_model_create_mrf_hierarchical_cpp`, nug, method, n_colors, emission, n_aux_sweeps)
}

model_has_emission_cpp <- function(model) {
  .Call(`_mdgm_model_has_emission_cpp`, model)
}

model_nvertices_cpp <- function(model) {
  .Call(`_mdgm_model_nvertices_cpp`, model)
}

model_ncolors_cpp <- function(model) {
  .Call(`_mdgm_model_ncolors_cpp`, model)
}

model_emission_type_cpp <- function(model) {
  .Call(`_mdgm_model_emission_type_cpp`, model)
}

sample_mrf_cpp <- function(nug, psi, n_colors, n_sweeps, rng) {
  .Call(`_mdgm_sample_mrf_cpp`, nug, psi, n_colors, n_sweeps, rng)
}

run_mcmc_cpp <- function(model, obs_data, obs_ptr, z_init, psi_init, theta_init, n_iterations, psi_tune, emission_prior_params, rng) {
  .Call(`_mdgm_run_mcmc_cpp`, model, obs_data, obs_ptr, z_init, psi_init, theta_init, n_iterations, psi_tune, emission_prior_params, rng)
}

nug_create_cpp <- function(nvertices, row, col, weights) {
  .Call(`_mdgm_nug_create_cpp`, nvertices, row, col, weights)
}

nug_sample_spanning_tree_cpp <- function(g, method, k, rng) {
  .Call(`_mdgm_nug_sample_spanning_tree_cpp`, g, method, k, rng)
}

nug_neighbors_cpp <- function(g, vertex) {
  .Call(`_mdgm_nug_neighbors_cpp`, g, vertex)
}

nug_neighbor_weights_cpp <- function(g, vertex) {
  .Call(`_mdgm_nug_neighbor_weights_cpp`, g, vertex)
}

nug_generate_regular_cpp <- function(nrows, ncols, order) {
  .Call(`_mdgm_nug_generate_regular_cpp`, nrows, ncols, order)
}

nug_nvertices_cpp <- function(g) {
  .Call(`_mdgm_nug_nvertices_cpp`, g)
}

nug_nedges_cpp <- function(g) {
  .Call(`_mdgm_nug_nedges_cpp`, g)
}

rng_create_cpp <- function() {
  .Call(`_mdgm_rng_create_cpp`)
}

rng_create_seed_cpp <- function(seed) {
  .Call(`_mdgm_rng_create_seed_cpp`, seed)
}

rng_set_seed_cpp <- function(rng, seed) {
  invisible(.Call(`_mdgm_rng_set_seed_cpp`, rng, seed))
}

rng_reseed_random_cpp <- function(rng) {
  invisible(.Call(`_mdgm_rng_reseed_random_cpp`, rng))
}

rng_uniform_cpp <- function(rng, a, b) {
  .Call(`_mdgm_rng_uniform_cpp`, rng, a, b)
}

rng_uniform_int_cpp <- function(rng, a, b) {
  .Call(`_mdgm_rng_uniform_int_cpp`, rng, a, b)
}

rng_normal_cpp <- function(rng, mean, stddev) {
  .Call(`_mdgm_rng_normal_cpp`, rng, mean, stddev)
}

rng_discrete_cpp <- function(rng, weights) {
  .Call(`_mdgm_rng_discrete_cpp`, rng, weights)
}
