# Generated by cpp11: do not edit by hand

undirected_graph_create_cpp <- function(nvertices, row, col, weights) {
  .Call(`_mdgm_undirected_graph_create_cpp`, nvertices, row, col, weights)
}

undirected_graph_sample_spanning_tree_cpp <- function(g, method, k, rng) {
  .Call(`_mdgm_undirected_graph_sample_spanning_tree_cpp`, g, method, k, rng)
}

undirected_graph_neighbors_cpp <- function(g, vertex) {
  .Call(`_mdgm_undirected_graph_neighbors_cpp`, g, vertex)
}

undirected_graph_nvertices_cpp <- function(g) {
  .Call(`_mdgm_undirected_graph_nvertices_cpp`, g)
}

undirected_graph_nedges_cpp <- function(g) {
  .Call(`_mdgm_undirected_graph_nedges_cpp`, g)
}

rng_create_cpp <- function() {
  .Call(`_mdgm_rng_create_cpp`)
}

rng_create_seed_cpp <- function(seed) {
  .Call(`_mdgm_rng_create_seed_cpp`, seed)
}
